/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package com.mycompany.booktrackerapp;

import java.util.List;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import org.json.JSONObject;
import org.json.JSONArray;
import java.io.BufferedReader;
import java.io.File;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;
import java.io.FileWriter; 
import java.io.FileReader; 
import java.io.IOException;
import java.time.LocalDate;
import java.util.Locale;
import javax.swing.SwingUtilities;

import java.lang.Runnable;
import java.util.logging.Level;
import javax.swing.SwingWorker;

/**
 *
 * @author Andi
 */
public class BookTrackerFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BookTrackerFrame.class.getName());
    private List<MediaItem>bookList=new ArrayList<>();
    private List<MediaItem>eBookList=new ArrayList<>();
    private List<MediaItem>audioBookList=new ArrayList<>();
    private User currentUser;
    /**
     * Creates new form BookTrackerFrame
     */
    public BookTrackerFrame() {
        initComponents();
        initializeUser();
        CombCategory.removeAllItems();
        CombCategory.addItem("Fantasy");
        CombCategory.addItem("Romance");
        CombCategory.addItem("Thriller");
        CombCategory.addItem("Young Adult (EN)");
        CombCategory.addItem("Young Adult (HU)");
        CombCategory.addItem("Author: Rebecca Yarros");
        CombCategory.addItem("Author: Colleen Hoover");
        CombCategory.addItem("Author: Ana Huang");
        CombCategory.addItem("Author: Leiner Laura");
        CombCategory.addItem("Category: AudioBook");
    }
    
    private void initializeUser(){
        String username=JOptionPane.showInputDialog(this,"Please give your username: ","Username Login", JOptionPane.PLAIN_MESSAGE);
    
        if(username != null && !username.trim().isEmpty()){
            String email=JOptionPane.showInputDialog(this,"Please give your email: ", "Email Address", JOptionPane.PLAIN_MESSAGE);
            
            if(email != null && !email.trim().isEmpty()){
                currentUser=new User(username.trim(), email.trim());
            }
            else{
                currentUser=new User(username.trim(), username.trim() + "@booktracker.com");
                JOptionPane.showMessageDialog(this, "Logged in as " + username.trim() + " (default email used).", "Login Info", JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            currentUser=new User("Guest","guest@example.com");
            JOptionPane.showMessageDialog(this, "Logged in as Guest.", "Login Info", JOptionPane.INFORMATION_MESSAGE);
        }
        
       if (currentUser != null) { 
            loadDataFromJSON(); 
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jlblAuthor = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ButtonAddBook = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        outputTxt = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        userOutputTxt = new javax.swing.JTextArea();
        CombCategory = new javax.swing.JComboBox<>();
        LoadButton = new javax.swing.JButton();
        selectMyBooks = new javax.swing.JButton();
        txtTitle = new javax.swing.JTextField();
        jTxtPublication = new javax.swing.JTextField();
        JtxtAuthor = new javax.swing.JTextField();
        jTxtISBN = new javax.swing.JTextField();
        jTxtPage = new javax.swing.JTextField();
        listMyBooksButton = new javax.swing.JButton();
        txtSelectBookTitle = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setText("Title:");
        lblTitle.setName("lblTitle"); // NOI18N

        jlblAuthor.setText("Author:");
        jlblAuthor.setName("JlblAuthor"); // NOI18N

        jLabel2.setText("Publication Year:");
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setText("ISBN:");
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setText("Page:");
        jLabel4.setName("jLabel4"); // NOI18N

        ButtonAddBook.setText("addBook");
        ButtonAddBook.setName("buttonAddBook"); // NOI18N
        ButtonAddBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAddBookActionPerformed(evt);
            }
        });

        jScrollPane1.setName("outputTxt"); // NOI18N

        outputTxt.setColumns(20);
        outputTxt.setRows(5);
        jScrollPane1.setViewportView(outputTxt);

        userOutputTxt.setColumns(20);
        userOutputTxt.setRows(5);
        userOutputTxt.setName("userOutputTxt"); // NOI18N
        jScrollPane2.setViewportView(userOutputTxt);

        CombCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fantasy", "Romance", "Thriller", "Young Adult(EN)", "Young Adult(HU)", "Author: Rebecca Yarros", "Author: Colleen Hoover" }));
        CombCategory.setName("CombCategory"); // NOI18N
        CombCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CombCategoryActionPerformed(evt);
            }
        });

        LoadButton.setText("LoadBook");
        LoadButton.setName("LoadButton"); // NOI18N
        LoadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadButtonActionPerformed(evt);
            }
        });

        selectMyBooks.setText("SelectBook");
        selectMyBooks.setName("selectMyBooks"); // NOI18N
        selectMyBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectMyBooksActionPerformed(evt);
            }
        });

        txtTitle.setText("txtTitle");

        jTxtPublication.setText("txtYear");

        JtxtAuthor.setText("txtAuthor");

        jTxtISBN.setText("txtISBN");
        jTxtISBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtISBNActionPerformed(evt);
            }
        });

        jTxtPage.setText("txtPage");
        jTxtPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtPageActionPerformed(evt);
            }
        });

        listMyBooksButton.setText("listMyBooks");
        listMyBooksButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listMyBooksButtonActionPerformed(evt);
            }
        });

        txtSelectBookTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSelectBookTitleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblAuthor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTitle)
                            .addComponent(JtxtAuthor, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jTxtPublication, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTxtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(81, 81, 81)
                        .addComponent(ButtonAddBook))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CombCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(443, 443, 443)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LoadButton)
                                .addGap(31, 31, 31)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtPage, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(selectMyBooks)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txtSelectBookTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(listMyBooksButton))))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtPublication, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblAuthor)
                    .addComponent(jLabel3)
                    .addComponent(ButtonAddBook)
                    .addComponent(JtxtAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LoadButton)
                                    .addComponent(txtSelectBookTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(listMyBooksButton)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selectMyBooks))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(CombCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        lblTitle.getAccessibleContext().setAccessibleName("");
        ButtonAddBook.getAccessibleContext().setAccessibleName("buttonAddBook");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void ButtonAddBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAddBookActionPerformed
        // TODO add your handling code here:  //ez a fo logika 
        try{
            String title=txtTitle.getText().trim();
            String author=JtxtAuthor.getText().trim();
            int publicationYear=Integer.parseInt(jTxtPublication.getText().trim());
            String ISBN=jTxtISBN.getText().trim();
            
            int page=Integer.parseInt(jTxtPage.getText().trim());
            MediaItem mediaItem;
            
            //polimorfikus letrehozas-oroklodes 
            //Ha az oldalszam kevesebb akkor AudioBook 
            if(page<0){
                String durationStr=JOptionPane.showInputDialog(this,"The page is < 0.Add the duration of the audiobook in min: ",JOptionPane.PLAIN_MESSAGE);
                int duration=Math.max(10,2 * title.length());//10 perc ,vagy a cim hosszanak 2x,ketszerese
                if(durationStr!=null && !durationStr.trim().isEmpty()){
                    try{
                       int parsedDuration=Integer.parseInt(durationStr.trim());
                        if(parsedDuration>0){
                            duration=parsedDuration;
                        }
                        else{
                            JOptionPane.showMessageDialog(this,"Not a positive number.Using default duration: "+duration+"min");
                        }
                    }
                    catch(NumberFormatException e){
                        JOptionPane.showMessageDialog(this,"Not a positive number.Using default duration: "+duration+"min");
                    }
                }
                mediaItem=new AudioBook(title,author,publicationYear,ISBN,duration);
            }
            //ha van oldalszam akkor Book
            else if(page>0){ 
              mediaItem=new Book(title,author,publicationYear,ISBN,page);
            }
            //ha az oldalszam=0; akkor EBook
            else{ 
               String sizeStr=JOptionPane.showInputDialog(this, "The page is 0.Add the size of Ebook(MB): ",JOptionPane.PLAIN_MESSAGE);
               int size=Math.max(10, 10 * title.length());
               if(sizeStr!=null && sizeStr.trim().isEmpty()){
                   //hibakezeles ha veletlenul a size nem szam
                   try{
                       int parsedSize=Integer.parseInt(sizeStr.trim());
                       if(parsedSize>0){
                           size=parsedSize;
                       }
                       else{
                           JOptionPane.showMessageDialog(this,"Not positive number.Using default size: "+size+ "MB");
                       }
                   }
                   catch(NumberFormatException e){
                       JOptionPane.showMessageDialog(this, "Invalid size formatUsing default size: "+size+"MB");
                   }
               }
              mediaItem=new EBook(title,author,publicationYear,ISBN,size); 
            }
            
            JOptionPane.showMessageDialog(this, mediaItem.getTitle() + "price: " +mediaItem.calculatePrice() + JOptionPane.INFORMATION_MESSAGE);
            
            //beolvassuk az olvasasi adatokat-rating,status,review
            String statusStr=JOptionPane.showInputDialog(this,"Enter your status(READ,IN_PROGRESS,WISHLIST): ",JOptionPane.PLAIN_MESSAGE);
            String ratingStr = JOptionPane.showInputDialog(this, "Enter your rating(1-5): ",JOptionPane.PLAIN_MESSAGE);
            String review=JOptionPane.showInputDialog(this, "Enter your review: ",JOptionPane.PLAIN_MESSAGE);
            
            int rating=0;
            if(ratingStr != null && !ratingStr.trim().isEmpty()){
                try{
                    rating=Integer.parseInt(ratingStr.trim());
                    if(rating < 1 || rating > 5){
                        rating=0; 
                    }
                }
                catch(NumberFormatException e){
                    rating=0;
                }
            }
          
            ReadingItem.Status status= ReadingItem.Status.WISHLIST;
            if(statusStr != null){
               status = ReadingItem.Status.valueOf(statusStr.replace(" ", "_").toUpperCase());
            }
            
            ReadingItem item = new ReadingItem(mediaItem, rating, (review != null ? review.trim() : ""), null, null, status);
            
            item.setStatus(status);
            
            currentUser.addReadingItem(item);
            
            saveDataInJSON(); 
            
            UpdateReadingList();
            
            // Törlés
            txtTitle.setText("");
            JtxtAuthor.setText("");
            jTxtPublication.setText("");
            jTxtISBN.setText("");
            jTxtPage.setText("");
        }
        catch(NumberFormatException e){
          JOptionPane.showMessageDialog(this, "The year, page, rating must be integer.");
        }
        catch(IllegalArgumentException e){
             JOptionPane.showMessageDialog(this, "Invalid status.Please use: READ,IN_PROGRESS,WISHLIST");
        }
    }//GEN-LAST:event_ButtonAddBookActionPerformed
  /*  private void fetchBooksFromAPI(String urlString){
        
        try{
            //kapcsolodas az URL-hez
            URL url=new URL(urlString);
            HttpURLConnection conn=(HttpURLConnection) url.openConnection();
            conn.setRequestMethod("GET");
            
            //valasz beolvasasa
            BufferedReader reader= new BufferedReader(new InputStreamReader(conn.getInputStream(),"UTF-8"));
            StringBuilder response=new StringBuilder();
            String line;
            
            while ((line = reader.readLine()) != null) {
                 response.append(line);
                 }    
            
            reader.close();
        
        //JSON feldolgozasa a Google Books API-hoz
        JSONObject json = new JSONObject(response.toString());
        
        JSONArray bookEntries =json.optJSONArray("items");
        
        bookList.clear();
        eBookList.clear();
        
        if(bookEntries == null){
            JOptionPane.showMessageDialog(this, "No books was found for this category");
            updateOutputTxt();
            return;
        }

          // json book objektumok
          for(int i=0;i<bookEntries.length();++i){
               JSONObject itemObj=bookEntries.getJSONObject(i);
               
               JSONObject volumeInfo = itemObj.optJSONObject("volumeInfo");
               if (volumeInfo == null) continue;
               
               String title=volumeInfo.optString("title", "unknown Title");
               String author="Unknown Author";
               
               JSONArray authors=volumeInfo.optJSONArray("authors");
               if(authors != null && authors.length()>0){ 
                    author=authors.getString(0);
               }
               

             int publicationYear = 0;
             String publishedDate=volumeInfo.optString("publishedDate","");
             
             if(!publishedDate.isEmpty()){
                try{
                    //AI-t megkerdeztem hogyan tehetem lathatova a publicationYear-t
                    String yearStr=publishedDate.substring(0,Math.min(publishedDate.length(),4 ));
                    publicationYear=Integer.parseInt(yearStr);
                }
                catch(NumberFormatException e){
                    publicationYear=0;
                }
             }
             
             int page=volumeInfo.optInt("pageCount",0);
             String ISBN= "N/A";
             JSONArray identifiers=volumeInfo.optJSONArray("industryIdentifiers");
             if(identifiers!=null){
                 for(int j=0;j<identifiers.length();++j){
                     JSONObject identifier=identifiers.getJSONObject(j);
                     String type= identifier.optString("type");
                     if(type.equals("ISBN_13")){
                         ISBN=identifier.optString("identifier");
                         break;
                     }
                 }
             }
             
             MediaItem mediaItem;
             if(page>0){
                 mediaItem=new Book(title,author,publicationYear,ISBN,page);
                 bookList.add(mediaItem);
             }
             else{
                 int defaultSizeMB=Math.max(10, title.length() * 5);
                 mediaItem=new EBook(title,author,publicationYear,ISBN,defaultSizeMB);
                 eBookList.add(mediaItem);
             }
             
          }   
        updateOutputTxt();
      }
        catch(Exception e){
        JOptionPane.showMessageDialog(this, "Error loading books: " + e.getMessage());
        }
    }
    
    private void updateOutputTxt(){
        StringBuilder sb=new StringBuilder();
        if(!bookList.isEmpty()){
            sb.append("--BOOKS\n--");
            for(MediaItem book : bookList){
               Book selectedBook = (Book) book;
                sb.append(book.getTitle())
                  .append(" by ").append(selectedBook.getAuthor())
                  .append(" (").append(selectedBook.getPublicationYear()).append(")")
                  .append(", ISBN: ").append(selectedBook.getISBN())
                  .append(", ").append(selectedBook.getPage()).append("pages")
                  .append("\n"); 
            }
        }
        
        if(!eBookList.isEmpty()){
           if(!bookList.isEmpty()){
               sb.append("\n");
           }
          sb.append("--E-BOOKS\n--");
          for(MediaItem book : eBookList){
                EBook selectedEBook = (EBook) book;
                sb.append("E-Book: ")
                  .append(book.getTitle())
                  .append(" by ").append(selectedEBook.getAuthor())
                  .append(" (").append(selectedEBook.getPublicationYear()).append(")")
                  .append(", ISBN: ").append(selectedEBook.getISBN())
                  .append(", Size: ").append(selectedEBook.getFileSizeMB()).append(" MB")
                  .append("\n");
            }
        }
        
        if(bookList.isEmpty() && eBookList.isEmpty()){
            sb.append("No books loaded from API");
        }
        outputTxt.setText(sb.toString());
    }
    
   */
    private void jTxtISBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtISBNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtISBNActionPerformed

    private void jTxtPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtPageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtPageActionPerformed

//ez a loadbutton metodus az API-bol kategoria szerint meghivja ,lekeri a neki tartozo linket,api-t
    
    private void LoadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadButtonActionPerformed
       String selected = (String)CombCategory.getSelectedItem();
       String url="";
       final String GOOGLE_BOOKS_BASE_URL = "https://www.googleapis.com/books/v1/volumes?q=";
       final int MAX_RESULTS=40;
        
       if (selected == null || selected.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please select a category!");
        return;
       }
        
        if(selected != null)
            switch (selected) {
            case "Fantasy":
                url=GOOGLE_BOOKS_BASE_URL + "subject:Fantasy&orderBy=newest&maxResults=" + MAX_RESULTS;
                break;
            case "Romance":
                url=GOOGLE_BOOKS_BASE_URL + "subject:Romance&orderBy=relevance&maxResults=" + MAX_RESULTS;
                break;
            case "Thriller":
                url=GOOGLE_BOOKS_BASE_URL + "subject:Thriller&maxResults=" + MAX_RESULTS;
                break;
            case "Young Adult (EN)":
                url=GOOGLE_BOOKS_BASE_URL + "subject:fiction+romance&langRestrict=en&maxResults=" + MAX_RESULTS;
                break;
            case "Young Adult (HU)":
                url=GOOGLE_BOOKS_BASE_URL + "subject:fiction=thriller&langRestrict=hu&maxResults=" + MAX_RESULTS;
                break;
            case "Author: Rebecca Yarros":
                 url=GOOGLE_BOOKS_BASE_URL + "inauthor:Rebecca+Yarros&maxResults=" + MAX_RESULTS; 
                break;
            case "Author: Colleen Hoover":
                url=GOOGLE_BOOKS_BASE_URL + "inauthor:Colleen+Hoover&maxResults=" + MAX_RESULTS;
                break;
            case "Author: Ana Huang":
                url=GOOGLE_BOOKS_BASE_URL + "inauthor:Ana+Huang&maxResults=" + MAX_RESULTS;
                break;
            case "Author: Leiner Laura":
                url=GOOGLE_BOOKS_BASE_URL + "inauthor:Leiner+Laura&maxResults=" + MAX_RESULTS;
                break;
            case "Category: AudioBook":
                url=GOOGLE_BOOKS_BASE_URL + "audiobook+OR+listen&orderBy=newest"
                        + "&maxResults=" + MAX_RESULTS;
                break;
            default:
                JOptionPane.showMessageDialog(this,"Choose another category.");
                break;
        }
        
       /* if(url.startsWith("https://")){
          fetchBooksFromAPI(url);
        }
        else if(!url.isEmpty()){
            JOptionPane.showMessageDialog(this, "Error loading books.");
        }*/
        
        final String finalUrl = url;
        
        if(finalUrl.startsWith("https://")){
            // UI visszajelzés a fő szálon
            outputTxt.setText("Loading books from API..."); 
            
            // ÚJ: Elindítja a hosszantartó munkát egy új Thread-en
            new Thread(new BookSearchRunnable(finalUrl) {}).start();
            
        }
        else if(!finalUrl.isEmpty()){
            JOptionPane.showMessageDialog(this, "Error loading books.");
        }
    }//GEN-LAST:event_LoadButtonActionPerformed

    private void selectMyBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectMyBooksActionPerformed
        // TODO add your handling code here:
        try {
            String enteredTitle = txtSelectBookTitle.getText();

            if (enteredTitle == null || enteredTitle.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please select the title of the book in the LEFT list (API results).", "Selection Error", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Kereses a bookList-ben a kivalasztott konyv utan
            MediaItem selectedBook = null;
           
            String searchTitle = enteredTitle.trim();

            for (MediaItem book : bookList) {
                if (book.getTitle().contains(searchTitle)) {
                    selectedBook = book;
                    break;
                }
            }
            
            if (selectedBook == null) {
              for(MediaItem book : eBookList){
                  if(book.getTitle().contains(searchTitle)){
                      selectedBook=book;
                  }
              }
           }

            if (selectedBook == null) {
                JOptionPane.showMessageDialog(this, "The selected title was not found in the loaded list.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Status, Rating, Review adatainak beolvasasa
            String statusStr = JOptionPane.showInputDialog(this, "Set the status for " + selectedBook.getTitle() + "READ,IN_PROGRESS,WISHLIST", JOptionPane.PLAIN_MESSAGE);
            if (statusStr == null) return;

            String ratingStr = JOptionPane.showInputDialog(this, "Enter your rating (1-5): ", JOptionPane.PLAIN_MESSAGE);
            String review = JOptionPane.showInputDialog(this, "Enter your review: ", JOptionPane.PLAIN_MESSAGE);

            int rating = 0;
            if(ratingStr != null && !ratingStr.trim().isEmpty()){
                try{
                    rating=Integer.parseInt(ratingStr.trim());
                    if(rating < 1 || rating > 5){
                        rating=0;
                    }
                }
                catch(NumberFormatException e){
                    JOptionPane.showMessageDialog(this, "Invalid rating.");
                    rating=0;
                }
            }

            ReadingItem.Status status=ReadingItem.Status.valueOf(statusStr.replace(" ", "_").toUpperCase());
            String opinion=(review!=null)?review.trim() : "";

            ReadingItem item=new ReadingItem(selectedBook, rating, opinion, null, null, status);
            item.setStatus(status);
            currentUser.addReadingItem(item);

            saveDataInJSON(); // MENTÉS

            JOptionPane.showMessageDialog(this,selectedBook.getTitle() + " added to your list as " + status + ".", "Success", JOptionPane.INFORMATION_MESSAGE);

            //UpdateReadingList();
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error when you are selecting the books " + e.getMessage());
        }
    }//GEN-LAST:event_selectMyBooksActionPerformed

    private void listMyBooksButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listMyBooksButtonActionPerformed
        // TODO add your handling code here:
        saveDataInJSON();
        UpdateReadingList();
    }//GEN-LAST:event_listMyBooksButtonActionPerformed

    private void txtSelectBookTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSelectBookTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSelectBookTitleActionPerformed

    private void CombCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CombCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CombCategoryActionPerformed
    
    private void UpdateReadingList(){
        StringBuilder sb=new StringBuilder();
        sb.append(currentUser.getusername()).append("'s reading list:\n");
        sb.append("Email: ").append(currentUser.getEmail()).append("\n");
        
        //ha nincsenek olvasasi bejegyzesei
        if(currentUser.getReadingList().isEmpty()){
            sb.append("You don't have a book in your reading list yet.");
        } 
        else{
            for(int i=0;i<currentUser.getReadingList().size();++i){
                ReadingItem item= currentUser.getReadingList().get(i);
                MediaItem book= item.getBook();
                
                sb.append("\nTitle:").append(book.getTitle())
                  .append("\nAuthor:\n ").append(book.getAuthor());
                
                sb.append("\nISBN:\n" ).append(book.getISBN());
                
                if(book instanceof Book){
                    Book selectedBook= (Book) book;
                    if(selectedBook.getPage()>0){
                       sb.append("\nPages: ").append(selectedBook.getPage());
                    }
                    else{
                        sb.append("\nPages: 0");
                    }
                }
                else if(book instanceof EBook){
                    EBook selectedEBook= (EBook) book;
                    double sizeMB = selectedEBook.getFileSizeMB();
                    if(sizeMB>0){
                     sb.append("\nSize: ").append(sizeMB).append("MB");  
                    }
                    else{
                     sb.append("\nSize: 0MB");
                    }
                  sb.append("\nPrice:\n ").append(String.format("%.2f", book.calculatePrice()));
                }
                else if(book instanceof AudioBook){
                    AudioBook selectedAudioBook= (AudioBook) book;
                    int duration=selectedAudioBook.getDurationInMinutes();
                    if(duration>0){
                        sb.append("Duration: ").append(duration).append("min");
                    }
                    else{
                        sb.append("\nDuration: 0 min");
                    }
                   sb.append("\nPrice:\n ").append(String.format("%.2f",book.calculatePrice()));
                }
                
                sb.append("\nStatus:\n").append(item.getStatus());
                
                if(item.getRating()>0){
                    sb.append("\nRating: ").append(item.getRating()).append("/5");
                }
                
                if(item.getReview()!=null && !item.getReview().trim().isEmpty()){
                    sb.append("\nReview: ").append(item.getReview()).append(" ");
                }
                sb.append("\n");
            }
        }
        
        userOutputTxt.setText(sb.toString());
    } 
    
     private void saveDataInJSON(){
        if(currentUser==null) return;
        
        //itt azert kell az egesz mappa mert maskepp nem fogadja el, tolti be 
        final String filename = "src/main/java/com/mycompany/booktrackerapp/myBooks.json";
        JSONArray readingListJson = new JSONArray();
        
        JSONObject mainJson = new JSONObject();
        mainJson.put("username", currentUser.getusername());
        mainJson.put("email", currentUser.getEmail());

        for(ReadingItem item : currentUser.getReadingList()){
            MediaItem book = item.getBook();
            if(book == null) continue;

            JSONObject itemJson = new JSONObject();
            itemJson.put("title", book.getTitle());
            itemJson.put("author", book.getAuthor());
            itemJson.put("publicationYear", book.getPublicationYear());
            itemJson.put("ISBN", book.getISBN());
            
            if(book instanceof Book){
                itemJson.put("page", ((Book) book).getPage());
            }
            else if(book instanceof EBook){
                itemJson.put("fileSizeMB", ((EBook) book).getFileSizeMB());
            }
            else if(book instanceof AudioBook){
                itemJson.put("durationInMinutes",((AudioBook) book).getDurationInMinutes());
            }
            
            itemJson.put("rating", item.getRating());
            itemJson.put("review", item.getReview());
            itemJson.put("status", item.getStatus().name());

            if(item.getStartDate()!=null){
                itemJson.put("startDate", item.getStartDate().toString());
            }
            if(item.getEndDate()!=null){
                itemJson.put("endDate", item.getEndDate().toString());
            }

            readingListJson.put(itemJson);
        }

        try(FileWriter file = new FileWriter(filename)){
            file.write(readingListJson.toString(4));
        }
        catch(IOException e){
            logger.log(Level.WARNING, "Error saving reading list", e);
            JOptionPane.showMessageDialog(this, "Error saving the data: " + e.getMessage());
        }
    }
    
     private void loadDataFromJSON(){
        if(currentUser==null) return;

        final String filename = "src/main/java/com/mycompany/booktrackerapp/myBooks.json";
        File file = new File(filename);
        if(!file.exists()){
            return;
        }

        StringBuilder sb = new StringBuilder();
        try(BufferedReader reader = new BufferedReader(new FileReader(file))){
            String line;
            while((line = reader.readLine()) != null){
                sb.append(line);
            }
        }
        catch(IOException e){
            logger.log(Level.WARNING, "Error reading saved data", e);
            JOptionPane.showMessageDialog(this, "Error loading the json data: " + e.getMessage());
            return;
        }

        String jsonString = sb.toString().trim();
        if(jsonString.isEmpty()){
            return;
        }

        try{
            JSONArray readingListArray = new JSONArray(jsonString);
            currentUser.getReadingList().clear();

            for(int i=0;i<readingListArray.length();i++){
                JSONObject itemJson = readingListArray.getJSONObject(i);

                String title = itemJson.optString("title", "");
                String author = itemJson.optString("author", "");
                int publicationYear = itemJson.optInt("publicationYear", 0);
                String ISBN = itemJson.optString("ISBN", "");
                int page = itemJson.optInt("page", itemJson.optInt("pages", 0));
                int duration=itemJson.optInt("durationInMinutes",0);

                //Book book = new Book(title, author, publicationYear, ISBN, page);
                
                MediaItem book;
                if(page>0){
                    book=new Book(title, author, publicationYear, ISBN, page);
                }
                else if(duration>0){
                    book=new AudioBook(title, author, publicationYear, ISBN , duration);
                }
                else{
                  int fileSize=itemJson.optInt("fileSizeMB",10);
                  book=new EBook(title, author, publicationYear, ISBN, fileSize);
                }
                
                int rating = itemJson.optInt("rating", 0);
                String review = itemJson.optString("review", "");
                String statusStr = itemJson.optString("status", ReadingItem.Status.WISHLIST.name());

                LocalDate startDate = itemJson.has("startDate") ? LocalDate.parse(itemJson.getString("startDate")) : null;
                LocalDate endDate = itemJson.has("endDate") ? LocalDate.parse(itemJson.getString("endDate")) : null;

                ReadingItem.Status status;
                try{
                    status = ReadingItem.Status.valueOf(statusStr);
                }
                catch(IllegalArgumentException ex){
                    status = ReadingItem.Status.WISHLIST;
                }

                ReadingItem item = new ReadingItem(book, rating, review, startDate, endDate, status);
                currentUser.addReadingItem(item);
            }

            UpdateReadingList();
        }
        catch(Exception e){
            logger.log(Level.WARNING, "Error parsing saved data", e);
            JOptionPane.showMessageDialog(this, "Error loading the json data: " + e.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BookTrackerFrame().setVisible(true));
    }
    
 private abstract class BookSearchRunnable implements Runnable {
    
        private String urlString = "";

    public BookSearchRunnable(String urlString){
        this.urlString=urlString;
    }

    @Override
    public void run(){
        String resultText = "Error loading books."; // Alapértelmezett hibaüzenet
            
            try {
                //A FETCHBOOKSFROMAPI logika
                URL url=new URL(urlString);
                HttpURLConnection conn=(HttpURLConnection) url.openConnection();
                conn.setRequestMethod("GET");
                
                BufferedReader reader= new BufferedReader(new InputStreamReader(conn.getInputStream(),"UTF-8"));
                StringBuilder response=new StringBuilder();
                String line;
                
                while ((line = reader.readLine()) != null) {
                     response.append(line);
                     }    
                
                reader.close();
            
                // --- ADATFELDOLGOZAS ---
                JSONObject json = new JSONObject(response.toString());
                JSONArray bookEntries =json.optJSONArray("items");
                
                bookList.clear();
                eBookList.clear();
                audioBookList.clear();
                
                if(bookEntries == null){
                    resultText = "No books was found for this category";
                } else {

                    //JSON feldolgozas 
                    for(int i=0;i<bookEntries.length();++i){
                        JSONObject itemObj=bookEntries.getJSONObject(i);
                        
                        JSONObject volumeInfo = itemObj.optJSONObject("volumeInfo");
                        if (volumeInfo == null) continue;
                        
                        String title=volumeInfo.optString("title", "unknown Title");
                        String author="Unknown Author";
                        
                        JSONArray authors=volumeInfo.optJSONArray("authors");
                        if(authors != null && authors.length()>0){ 
                             author=authors.getString(0);
                        }
                        
                        int publicationYear = 0;
                        String publishedDate=volumeInfo.optString("publishedDate","");
                        
                        if(!publishedDate.isEmpty()){
                           try{
                               String yearStr=publishedDate.substring(0,Math.min(publishedDate.length(),4 ));
                               publicationYear=Integer.parseInt(yearStr);
                           }
                           catch(NumberFormatException e){
                               publicationYear=0;
                           }
                        }
                        
                        int page=volumeInfo.optInt("pageCount",0);
                        String ISBN= "N/A";
                        JSONArray identifiers=volumeInfo.optJSONArray("industryIdentifiers");
                        if(identifiers!=null){
                            for(int j=0;j<identifiers.length();++j){
                                JSONObject identifier=identifiers.getJSONObject(j);
                                String type= identifier.optString("type");
                                if(type.equals("ISBN_13")){
                                    ISBN=identifier.optString("identifier");
                                    break;
                                }
                            }
                        }
                        
                        MediaItem mediaItem;
                        if(urlString.contains("audiobook+OR+listen")){
                            int durationMin=Math.max(10, title.length() * 2);
                            mediaItem=new AudioBook(title,author,publicationYear,ISBN, durationMin);
                            audioBookList.add(mediaItem);
                        }
                        else if(page>0){
                            mediaItem=new Book(title,author,publicationYear,ISBN,page);
                            bookList.add(mediaItem);
                        }
                        else{
                            int defaultSizeMB=Math.max(10, title.length() * 5);
                            mediaItem=new EBook(title,author,publicationYear,ISBN,defaultSizeMB);
                            eBookList.add(mediaItem);
                        }
                    }
                    
                    // az updateOutputTxt logikaja
                    StringBuilder sb=new StringBuilder();
                    if(!bookList.isEmpty()){
                        sb.append("BOOKS\n--");
                        for(MediaItem book : bookList){
                           Book selectedBook = (Book) book;
                            sb.append(book.getTitle())
                              .append(" by ").append(selectedBook.getAuthor())
                              .append(" (").append(selectedBook.getPublicationYear()).append(")")
                              .append(", ISBN: ").append(selectedBook.getISBN())
                              .append(", ").append(selectedBook.getPage()).append("pages")
                              .append("\n"); 
                        }
                    }
                    
                    if(!eBookList.isEmpty()){
                       if(!bookList.isEmpty()){
                           sb.append("\n");
                       }
                      for(MediaItem book : eBookList){
                            EBook selectedEBook = (EBook) book;
                           sb.append("E-BOOKS\n: ")
                              .append(book.getTitle())
                              .append(" by ").append(selectedEBook.getAuthor())
                              .append(" (").append(selectedEBook.getPublicationYear()).append(")")
                              .append(", ISBN: ").append(selectedEBook.getISBN())
                              .append(", Size: ").append(selectedEBook.getFileSizeMB()).append(" MB")
                              .append("\n");
                        }
                    }
                    if(!audioBookList.isEmpty()){
                      if(!bookList.isEmpty() || eBookList.isEmpty()){
                          sb.append("\n");
                      }
                    }
                    //sb.append("AUDIO BOOKS\n---");
                    for(MediaItem book : audioBookList){
                       AudioBook selectedAudioBook=(AudioBook) book;
                       sb.append("AUDIO BOOKS\n: ")
                         .append(book.getTitle())
                         .append(" by ").append(selectedAudioBook.getAuthor())
                         .append(" (").append(selectedAudioBook.getPublicationYear()).append(")")
                         .append(", ISBN: ").append(selectedAudioBook.getISBN())
                         .append(", Duration: ").append(selectedAudioBook.getDurationInMinutes()).append(" min")
                         .append("\n");  
                    }
                  
                    if(bookList.isEmpty() && eBookList.isEmpty() && audioBookList.isEmpty()){
                        sb.append("No books loaded from API");
                    }
                    resultText = sb.toString();
                }

            } catch(Exception e) {
                logger.log(Level.WARNING, "Error loading books in thread", e);
                resultText = "Error loading books: " + e.getMessage();
            }
            
            final String finalResultText = resultText;
            
            SwingUtilities.invokeLater(new Runnable() {
                @Override
                public void run() {
                    outputTxt.setText(finalResultText);
                    if (finalResultText.startsWith("Error") || finalResultText.equals("No books was found for this category")) {
                        JOptionPane.showMessageDialog(BookTrackerFrame.this, finalResultText);
                    }
                }
            });
    }
 }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAddBook;
    private javax.swing.JComboBox<String> CombCategory;
    private javax.swing.JTextField JtxtAuthor;
    private javax.swing.JButton LoadButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTxtISBN;
    private javax.swing.JTextField jTxtPage;
    private javax.swing.JTextField jTxtPublication;
    private javax.swing.JLabel jlblAuthor;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JButton listMyBooksButton;
    private javax.swing.JTextArea outputTxt;
    private javax.swing.JButton selectMyBooks;
    private javax.swing.JTextField txtSelectBookTitle;
    private javax.swing.JTextField txtTitle;
    private javax.swing.JTextArea userOutputTxt;
    // End of variables declaration//GEN-END:variables
}
